description:
    Blog of the software developer Felipe Martins, aka fefas, with content that
    may help others developers to work better.

links:
    sourceCode: https://github.com/fefas/blog.fefas.net
    licenses:
        content: https://creativecommons.org/licenses/by-sa/4.0
        sourceCode: https://github.com/fefas/blog.fefas.net/blob/master/LICENSE

author:
    name: Felipe Martins
    nickname: fefas
    twitterNickname: eufefas
    email: me@fefas.net

    links:
        github: https://github.com/fefas
        twitter: https://twitter.com/eufefas
        stackOverflow: https://stackoverflow.com/users/4259675/felipe-martins
        linkedin: https://br.linkedin.com/in/fefas
        devto: https://dev.to/fefas
        medium: https://medium.com/@fefas

analyticsId: UA-53252365-5

timezone: America/Sao_Paulo
encoding: UTF-8

plugins:
    - jekyll-sitemap
    - jekyll-feed

sass:
    style: compressed

exclude:
    - Dockerfile.dev
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - netlify.toml
    - README.md
    - stack-dev.yml
