[build]
  publish = "_site/"
  command = "jekyll build --config '_config.yml,_config_dev.yml' --baseurl $DEPLOY_PRIME_URL"

[context.production]
  command = "jekyll build --config '_config.yml' --baseurl $URL"
