[build]
  publish = "_site/"
  command = "echo 'url: '$DEPLOY_PRIME_URL >> _config_dev.yml && jekyll build --config '_config.yml,_config_dev.yml' --future"

[context.production]
  command = "jekyll build --config '_config.yml' --future"
