[build]
  publish = "_site/"
  command = "jekyll build --config $CONFIG_FILES"
  environment = { CONFIG_FILES = "_config.yml,_config_dev.yml" }

[context.production]
  environment = { CONFIG_FILES = "_config.yml" }
