version: "3"

services:
    jekyll:
        build:
          context: ./
          dockerfile: Dockerfile.dev
        image: fefas/blog.fefas.net:dev
        ports:
            - 80:80
        volumes:
            - ./.git:/usr/src/.git
            - ./jekyll/:/usr/src/
