url: https://blog.fefas.net
sourceCodeLink: https://github.com/fefas/blog.fefas.net
description:
  Blog of the software developer Felipe Martins, aka fefas, with content that
  may help others developers to work better.

author:
  name: Felipe Martins
  nickname: fefas
  email: me@fefas.net
  twitter: eufefas
  stackoverflow: 4259675/felipe-martins

googleAnalyticsId: UA-53252365-5

timezone: America/Sao_Paulo
encoding: UTF-8

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
