timezone: America/Sao_Paulo
encoding: UTF-8

plugins:
  - jekyll-sitemap

googleAnalytics:
  id: UA-53252365-5

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
