url: https://blog.fefas.dev

timezone: Europe/Berlin
encoding: UTF-8
googleAnalyticsId: G-DFYZ727543

sourceCode: https://github.com/fefas/blog
contentLicense: https://creativecommons.org/licenses/by-sa/4.0

author:
  name: Felipe Martins
  email: mail@fefas.dev
  github: https://github.com/fefas
  linkedin: https://br.linkedin.com/in/fefas
  devto: https://dev.to/fefas
  medium: https://fefas.medium.com

defaults:
- scope:
    path: ""
    type: posts
  values:
    type: article
- scope:
    path: ""
    type: page
  values:
    type: website

plugins:
- jekyll-sitemap
- jekyll-feed

excerpt_separator: <!--excerpt-->
sass:
  style: compressed
