url: https://blog.fefas.dev
description: Felipe Martins on software engineering.

timezone: Europe/Berlin
encoding: UTF-8
googleAnalyticsId: G-DFYZ727543

sourceCode: https://github.com/fefas/blog
contentLicense: https://creativecommons.org/licenses/by-sa/4.0

author:
  name: Felipe Martins
  email: mail@fefas.dev
  linkedin: https://br.linkedin.com/in/fefas
  github: https://github.com/fefas
  devto: https://dev.to/fefas
  medium: https://fefas.medium.com

excerpt_separator: <!--excerpt-->

plugins:
- jekyll-sitemap
- jekyll-feed

sass:
  style: compressed
